<?php
define("Menu", "Expériences");
define("Menu_1", "Compétences");
define("Menu_2", '<a href="index.php?page=mesrea&css=%27.$css.%27">Portfolio</a>');
define("Menu_3", '<a href="image/Nora%20BOUROUIS%20CV%20CAWEB%20M2.pdf"> CV</a>');
define("Menu_4", "Contact");
define("MSG_top", "Bienvenue sur le");
define("MSG_top2", "site portfolio de Nora B.");
define("Titre_intro","A propos de moi");
define("MSG_INTRO", "Moi, c'est Nora. Je suis une future chef de projet et je souhaiterais travailler dans la communication digitale. Issue d'une formation professionnalisante en web et en localisation, j'ai été formée à tous les aspects du métier. Je suis disponible dès octobre 2018.");
define("Titre_BG_3","Mes domaines de compétences");
define("Titre_section_BG3_1", "Développement et intégration web");
define("msg_section_BG3_1","Lors de ma formation Caweb, j'ai eu l'occasion de participer à plusieurs projets de développement et intégration web. Découvrez l'ensemble de mes réalisations sur mon portfolio.");
define("Titre_section_BG3_2", "Communication digitale");
define("msg_section_BG3_2","Mon profil est aussi un profil de rédactrice web. En effet, j'ai rédigé de nombreuses actualités et articles pour le Conseil Départemental du Bas-Rhin dans le cadre de mon apprentissage. J'ai également contribué au blog du master Caweb en rédigeant deux articles traitant de l'actualité web.
");
define("Titre_section_BG3_3", "Localisation et traduction");
define("msg_section_BG3_3", "Issue d'un parcours linguistique, j'ai décidé de continuer sur cette lancée en me formant à la traduction de site web et à la localisation de jeux vidéo. J'ai notamment suivi une formation de dix heures dispensée par Google à ce propos.");
define("Titre_section_BG3_4","Gestion de projet");
define("msg_section_BG3_4","En l'espace de deux ans, j'ai géré deux projets d'envergure en tant que chef de projet : un projet de refonte d'une application et un projet de refonte de site web. J'ai également supervisé une équipe de community manager pour les réseaux sociaux du master Caweb. De la rédaction d'un cahier des charges jusqu'aux tests finaux et formation d'un donneur d'ordre : rien ne m'échappe. Je dispose également d'une formation à la méthode AGIL. (SCRUM, Kanban)");
define("Titre_Bg_4","Quelques détails");
define("Titre_section_BG4_1","Je développe en");
define("Titre_section_BG4_2","Je parle ");
define("msg_section_BG4_2_1","Français");
define("msg_section_BG4_2_2","Anglais (C1)");
define("msg_section_BG4_2_3","Japonais (B2)");
define("Titre_section_BG4_3","Je maîtrise");
define("Titre_section_BG4_4","les logiciels suivants");
define("Titre_section_BG4_5","les CMS suivants");
define("Titre_Bg_5","Mon parcours");
define("Titre_section_BG5","Sortie de la nouvelle version de l'application Bas-Rhin à Vélo");
define("Role_BG5","Chef de projet");
define("Mission_BG5","Projet de refonte de l'application Bas-Rhin à vélo en collaboration avec l'équipe technique et la PAO afin d'améliorer l'ergonomie de l'application, le design associé et de rapatrier le Backoffice au CD67.");
define("Date_BG5","Juin 2018");
define("Titre_section_BG5_1","Apprentissage au Conseil Départemental du Bas-Rhin(CD67)");
define("Role_BG5_1","Responsable de l'application Bas-Rhin à Vélo.");
define("Mission_BG5_1","Rédaction web, community management");
define("Date_BG5_1","04/09/2017-30/09/2018");
define("Titre_section_BG5_2","Community management pour le Master Caweb");
define("Role_BG5_2","Chef de projet community manager");
define("Mission_BG5_2","Gestion d'une équipe de trois étudiantes et des quatre réseaux sociaux du master : Facebook, Twitter, Instagram et LinkedIn.");
define("Date_BG5_2","10/06/2017 - 01/06/2018");
define("Titre_section_BG5_3","Refonte du site web de l'entreprise Catra");
define("Role_BG5_3"," Co-chef de projet, intégrateur et développeur");
define("Mission_BG5_3","Refonte du site web de l'entreprise Catra en équipe de cinq personnes dans le cadre de ma première année de Master.");
define("Date_BG5_3","01/02/2017 - 01/06/2017");
define("Titre_section_BG5_4","Stage à l'agence de Relations Presse Wag Inc.");
define("Mission_BG5_4","Stage de fin de licence effectué dans une agence de Relations Presse. ");
define("Date_BG5_4","01/02/2016 - 01/04/2016");
define("Role_BG5_4","Stagiaire");
define("Titre_Bg6","Me contacter");
define("Label_nom","Nom : ");
define("Label_prenom","Prénom : ");
define("Label_mail","E-mail :  ");
define("Label_mess","Votre message :");
define("Titre_Bg7", "Pour en savoir plus sur moi ou mes projets");
define("Titre_Bg7_1", "Retrouvez-moi sur");
define("Envoyer", "Envoyer");
define("Footer", "Tous les droits réservés. Site portfolio de Nora.");
define("MSG_ok", "Votre message a bien été envoyé. Merci pour votre considération, je vous répondrai dans les plus brefs délais.");
define("MSG_erreur", "<p class='invalide'>L'adresse saisie n'est pas valide</p>");
define("MSG_erreur2","<p class='manque'>Un ou plusieurs champs obligatoire n'ont pas été remplis. Veuillez vérifier et essayer à nouveau.</p>");
define("", "");
define("", "");
?>